Update lower bounds
This commit updates the following lower bounds:

  template-haskell: 2.16 -> 2.17
  base: 4.14 -> 4.15

This ensures we don't try to build time >= 1.14 with GHC 8.10 or below,
which is not supported:

  lib\Data\Time\Clock\Internal\DiffTime.hs:83:18: error:
  Error:     Not in scope: type constructor or class ‘TH.Quote’

  lib\Data\Time\Clock\Internal\DiffTime.hs:83:44: error:
  Error:     Not in scope: type constructor or class ‘TH.Code’