Require GHC >= 7.10
Build failure:
```
[19 of 26] Compiling Data.Time.Format.Parse ( lib/Data/Time/Format/Parse.hs, dist/dist-sandbox-3798890a/build/Data/Time/Format/Parse.o )

lib/Data/Time/Format/Parse.hs:524:32: Not in scope: ‘<$>’

lib/Data/Time/Format/Parse.hs:524:53: Not in scope: ‘<*>’

lib/Data/Time/Format/Parse.hs:587:32: Not in scope: ‘<$>’

lib/Data/Time/Format/Parse.hs:587:53: Not in scope: ‘<*>’

lib/Data/Time/Format/Parse.hs:590:37: Not in scope: ‘<$>’

lib/Data/Time/Format/Parse.hs:593:39: Not in scope: ‘<$>’
me packages failed to install:
time-1.6 failed during the building phase. The exception was:
ExitFailure 1
```